[theme]
primaryColor = "#00FF87"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#161B22"
textColor = "#FFFFFF"

[browser]
gatherUsageStats = false

[server]
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 1
